- name: Configuring "{{ microservice_name }}"
  ansible.builtin.debug:
    msg: Building "{{ microservice_name }}" microservice

- name: Install dnf dependencies
  ansible.builtin.import_role:
    name: dnf_modules
    tasks_from: main.yml
  become: true

- name: Create User
  ansible.builtin.import_role:
    name: create_user
    tasks_from: main.yml
  become: true

- name: Ensure ~/.cache exists and has correct permissions
  ansible.builtin.file:
    path: "/home/{{ dir_owner }}/.cache"
    state: directory
    owner: "{{ dir_owner }}"
    group: "{{ dir_owner }}"
    mode: '0755'
    recurse: yes
  become: yes


- name: Create Directory
  ansible.builtin.import_role:
    name: create_directory
    tasks_from: main.yml

- name: Copy service file
  ansible.builtin.template:
    src: dispatch.service
    dest: /etc/systemd/system/dispatch.service
  become_user: "{{ dir_owner }}"

- name: Unzip files
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
    dest: "{{ directory_path }}"
    remote_src: yes
  become: true

- name: Execute permissions to user
  ansible.builtin.shell: "chown -R {{ dir_owner }}:{{ dir_owner }} {{ directory_path }}"
  become: yes

- name: Execute go commands
  ansible.builtin.shell: "cd {{ directory_path }} ; {{ item }}"
  loop: "{{ execute_go }}"
  become_user: "{{ dir_owner }}"

- name: create systemd service
  ansible.builtin.import_role:
    name: systemd
    tasks_from: main.yml