- name: Configuring "{{ microservice_name }}"
  ansible.builtin.debug:
    msg: Building "{{ microservice_name }}" microservice

- name: Install dnf dependencies
  ansible.builtin.import_role:
    name: dnf_modules
    tasks_from: main.yml

- name: Create User
  ansible.builtin.import_role:
    name: create_user
    tasks_from: main.yml

- name: Create Directory
  ansible.builtin.import_role:
    name: create_directory
    tasks_from: main.yml

- name: Unzip files
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
    dest: "{{ directory_path }}"
    remote_src: yes

- name: Execute go commands
  ansible.builtin.shell: "cd {{ directory_path }} ; go {{ item }}"
  loop: "{{ execute_go }}"

- name: create systemd service
  ansible.builtin.import_role:
    name: systemd
    tasks_from: main.yml