- name: Disable nginx module
  ansible.builtin.shell: dnf module disable {{ app_name }} -y ; dnf module enable {{ app_name }}:1.24 -y
  when: app_name == "nginx"

- name: "Install Unzip"
  ansible.builtin.dnf:
    name:
      - unzip
      - wget
    state: installed

- name: "installing {{ app_name }}"
  ansible.builtin.dnf:
    name: "{{ app_name }}-1:1.24.0-4.module_el9+1087+9adf8b0f"
    state: installed
    update_cache: true
  when: app_name == "nginx"

- name: "installing {{ app_name }}"
  ansible.builtin.dnf:
    name: "{{ app_name }}"
    state: installed
    update_cache: true
  when: app_name == "mongodb-org"

