- name: Disable nginx module
  ansible.builtin.shell: dnf module disable {{ app_name }} -y ; dnf module enable {{ app_name }}:1.24 -y

- name: "installing {{ app_name }}"
  dnf:
    name: "{{ app_name }}:1:1.24"
    state: installed
    update_cache: true
  when: app_name == "nginx"
