- name: Disable nginx module
  ansible.builtin.shell: dnf module disable nginx -y ; dnf module enable nginx:1.24 -y

- name: "installing {{ app_name }}"
  dnf:
    name: "{{ app_name }}:1.24"
    state: enabled
    update_cache: true
    when: app_name == "nginx"
