role_name: "shipping"
server: "shipping"
microservice_name: "shipping"
app_install:
  - { name: "maven", version: ""}
  - { name: "mysql", version: ""}
schemas:
  - "schema"
  - "app-user"
  - "master-data"
user: "roboshop"
directory_path: "/app"
cart_ip: "10.128.0.57"
mysql_ip: "10.128.0.57"
systemd_app_name: "shipping"
rb_password: "RoboShop@1"